# Generated by Django 5.2.8 on 2025-11-15 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_entrega', models.CharField(choices=[('entrega', 'Entrega'), ('retirada', 'Retirada')], default='entrega', max_length=10)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_frete', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('status', models.CharField(choices=[('recebido', 'Recebido'), ('em_preparo', 'Em Preparo'), ('saiu_para_entrega', 'Saiu para Entrega'), ('entregue', 'Entregue'), ('cancelado', 'Cancelado')], default='recebido', max_length=20)),
                ('pagamento_confirmado', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
